In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve

In [2]:
import pandas as pd
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

# Number of samples
n = 1000  

# Generate synthetic features
age = np.random.randint(18, 70, n)
income = np.random.randint(20000, 150000, n)
loan_amount = np.random.randint(1000, 50000, n)
credit_history = np.random.choice([0, 1], size=n, p=[0.3, 0.7])  # 70% good credit history
employment_status = np.random.choice([0, 1], size=n, p=[0.2, 0.8])  # 80% employed
num_credit_cards = np.random.randint(0, 6, n)
defaulted_before = np.random.choice([0, 1], size=n, p=[0.1, 0.9])  # 10% defaulted before

# Simple logic for target variable
creditworthy = (
    (income > 40000) &
    (credit_history == 1) &
    (employment_status == 1) &
    (loan_amount < 30000) &
    (defaulted_before == 0)
).astype(int)

# Create DataFrame
df = pd.DataFrame({
    "Age": age,
    "Income": income,
    "LoanAmount": loan_amount,
    "CreditHistory": credit_history,
    "EmploymentStatus": employment_status,
    "NumCreditCards": num_credit_cards,
    "DefaultedBefore": defaulted_before,
    "Creditworthy": creditworthy
})

# Save to CSV inside data/ folder
df.to_csv("../data/credit_data.csv", index=False)

df.head()

,Age,Income,LoanAmount,CreditHistory,EmploymentStatus,NumCreditCards,DefaultedBefore,Creditworthy
0,56,125186,19546,0,1,0,1,0
1,69,54674,20129,1,1,0,1,0
2,46,55854,2591,0,1,1,1,0
3,32,66271,12303,1,0,5,1,0
4,60,93688,31561,1,0,1,1,0